### ISSUE TITLE
Neo.Compiler Stack empty error

### ISSUE THREAD

**Issue by ctaggart** [imusify/imusify-incentify-smart-contract#4]
I get this error with the current code. I reproduced it vi an AppVeyor build #3.
```
C:\Users\camer\imusify\imusify-incentify-smart-contract [master ≡]> msbuild /t:rebuild /p:configuration=release /v:m
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  contract -> C:\Users\camer\imusify\imusify-incentify-smart-contract\contract\bin\Release\contract.dll
  Start NeoContract converter, Source File: C:\Users\camer\imusify\imusify-incentify-smart-contract\contract\bin\Release\contract.dll
  Neo.Compiler.MSIL console app v2.0.3.0
CONVERTTASK : Convert error : System.InvalidOperationException: Stack empty. [C:\Users\camer\imusify\imusify-incentify-smart-contract\contract\contract
.csproj]
     at System.Collections.Generic.Stack`1.Pop()
     at Neo.Compiler.MSIL.CctorSubVM.Parse(ILMethod from, AntsModule to)
     at Neo.Compiler.MSIL.ModuleConverter.Convert(ILModule _in)
     at Neo.Compiler.Program.Main(String[] args)
```

**Comment by ctaggart** [comment]
What I meant is that it that the error is reproducible on AppVeyor:

https://ci.appveyor.com/project/ctaggart/imusify-incentify-smart-contract/build/13
![image](https://user-images.githubusercontent.com/80104/31672269-020dd91c-b354-11e7-887d-7498c104b677.png)

If this project isn't being used, then let's close this.

**Comment by ctaggart** [comment]
Fixed by @geek96 with https://github.com/imusify/imusify-incentify-smart-contract/commit/64e4f79a64b86acadb49d99c7789e808b0d68d1e

Ran it on my CI https://ci.appveyor.com/project/ctaggart/imusify-incentify-smart-contract/build/19
